spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/e_commerce_platform?createDatabaseIfNotExist=true
    url: jdbc:mysql://viaduct.proxy.rlwy.net:25538/ecommerce_paltform?createDatabaseIfNotExist=true
    username: root
    password: Gmci@2001
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update


    database: mysql
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  ssl:
#    key-alias: spring-boot-https
    key-store: classpath:spring-boot-https.jks
#    key-store-type: JKS
#    password:
    key-store-password: Gmci@2001
  port: 8080
#      spring-boot-https
#      keytool -genkey -alias spring-boot-https -keyalg RSA -keysize 2048 -keystore spring-boot-https.jks -storepass Gmci@2001
